require 'rake/clean'

require_relative 'c_generate_command'
require_relative 'c_generate_ext_command'
require_relative 'generate_ext_enum_list'
require_relative 'generate_ext_command_list'

CLEAN.include( FileList['../ext/opengl_c/rogl_commands.c.inc',
                        '../ext/opengl_c/rogl_ext_commands.c.inc',
                        '../lib/opengl_ext_enum.rb',
                        '../lib/opengl_ext_command.rb',
               ] )


task 'default' => 'wrapper'

task 'wrapper' => ['command', 'ext_command', 'ext_enum_list', 'ext_command_list']

task 'command' => '../ext/opengl_c/rogl_commands.c.inc'
task 'ext_command' => '../ext/opengl_c/rogl_ext_commands.c.inc'
task 'ext_enum_list' => '../lib/opengl_ext_enum.rb'
task 'ext_command_list' => '../lib/opengl_ext_command.rb'

file '../ext/opengl_c/rogl_commands.c.inc' => './gl.xml' do |t|
  open('../ext/opengl_c/rogl_commands.c.inc', 'wb') do |file|
    GLCodeGenerator.generate_command(file)
  end
end

file '../ext/opengl_c/rogl_ext_commands.c.inc' => './gl.xml' do |t|
  open('../ext/opengl_c/rogl_ext_commands.c.inc', 'wb') do |file|
    GLExtCodeGenerator.generate_command(file)
  end
end

file '../lib/opengl_ext_command.rb' => './gl.xml' do |t|
  open('../lib/opengl_ext_command.rb', 'wb') do |file|
    generate_ext_command(file)
  end
end

file '../lib/opengl_ext_enum.rb' => './gl.xml' do |t|
  open('../lib/opengl_ext_enum.rb', 'wb') do |file|
    generate_ext_enum(file)
  end
end
